In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("berkayalan/retail-sales-data")

print("Path to dataset files:", path)

Path to dataset files: /home/codespace/.cache/kagglehub/datasets/berkayalan/retail-sales-data/versions/1

In [2]:
from pathlib import Path

dataset_path = Path(
    "/home/codespace/.cache/kagglehub/datasets/berkayalan/retail-sales-data/versions/1"
)

for path in dataset_path.rglob("*"):
    print("DIR " if path.is_dir() else "FILE", path)

FILE /home/codespace/.cache/kagglehub/datasets/berkayalan/retail-sales-data/versions/1/store_cities.csv
FILE /home/codespace/.cache/kagglehub/datasets/berkayalan/retail-sales-data/versions/1/product_hierarchy.csv
DIR  /home/codespace/.cache/kagglehub/datasets/berkayalan/retail-sales-data/versions/1/sales.csv
FILE /home/codespace/.cache/kagglehub/datasets/berkayalan/retail-sales-data/versions/1/sales.csv/sales.csv

In [3]:
from pathlib import Path

dataset_path = Path(
    "/home/codespace/.cache/kagglehub/datasets/berkayalan/retail-sales-data/versions/1"
)

for file in dataset_path.rglob("*"):
    if file.is_file():
        print(file)

/home/codespace/.cache/kagglehub/datasets/berkayalan/retail-sales-data/versions/1/store_cities.csv
/home/codespace/.cache/kagglehub/datasets/berkayalan/retail-sales-data/versions/1/product_hierarchy.csv
/home/codespace/.cache/kagglehub/datasets/berkayalan/retail-sales-data/versions/1/sales.csv/sales.csv

You can try this code below it is going to result in Kernel Crash. The reason being that the @sales.csv file is actually about 1 gb large. And loading it at once crashed the kernel.

In [ ]:
import pandas as pd

file_path = (
    "/home/codespace/.cache/kagglehub/datasets/berkayalan/"
    "retail-sales-data/versions/1/sales.csv/sales.csv"
)

df = pd.read_csv(file_path)
df.head()

The Code below is safe to use actually since we are limiting it to 100_000 rows.

In [4]:
import pandas as pd

file_path = (
    "/home/codespace/.cache/kagglehub/datasets/berkayalan/"
    "retail-sales-data/versions/1/sales.csv/sales.csv"
)

df = pd.read_csv(file_path, nrows=100_000)
df.head()

,product_id,store_id,date,sales,revenue,stock,price,promo_type_1,promo_bin_1,promo_type_2,promo_bin_2,promo_discount_2,promo_discount_type_2
0,P0001,S0002,2017-01-02,0.0,0.00,8.0,6.25,PR14,NaN,PR03,NaN,NaN,NaN
1,P0001,S0012,2017-01-02,1.0,5.30,0.0,6.25,PR14,NaN,PR03,NaN,NaN,NaN
2,P0001,S0013,2017-01-02,2.0,10.59,0.0,6.25,PR14,NaN,PR03,NaN,NaN,NaN
3,P0001,S0023,2017-01-02,0.0,0.00,6.0,6.25,PR14,NaN,PR03,NaN,NaN,NaN
4,P0001,S0025,2017-01-02,0.0,0.00,1.0,6.25,PR14,NaN,PR03,NaN,NaN,NaN

In [5]:
df["date"] = pd.to_datetime(df["date"])

In [6]:
df.head()

,product_id,store_id,date,sales,revenue,stock,price,promo_type_1,promo_bin_1,promo_type_2,promo_bin_2,promo_discount_2,promo_discount_type_2
0,P0001,S0002,2017-01-02,0.0,0.00,8.0,6.25,PR14,NaN,PR03,NaN,NaN,NaN
1,P0001,S0012,2017-01-02,1.0,5.30,0.0,6.25,PR14,NaN,PR03,NaN,NaN,NaN
2,P0001,S0013,2017-01-02,2.0,10.59,0.0,6.25,PR14,NaN,PR03,NaN,NaN,NaN
3,P0001,S0023,2017-01-02,0.0,0.00,6.0,6.25,PR14,NaN,PR03,NaN,NaN,NaN
4,P0001,S0025,2017-01-02,0.0,0.00,1.0,6.25,PR14,NaN,PR03,NaN,NaN,NaN

In [7]:
df.shape

(100000, 13)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   product_id             100000 non-null  str
 1   store_id               100000 non-null  str
 2   date                   100000 non-null  datetime64[us]
 3   sales                  100000 non-null  float64
 4   revenue                100000 non-null  float64
 5   stock                  100000 non-null  float64
 6   price                  98523 non-null   float64
 7   promo_type_1           100000 non-null  str
 8   promo_bin_1            10950 non-null   str
 9   promo_type_2           100000 non-null  str
 10  promo_bin_2            0 non-null       float64
 11  promo_discount_2       0 non-null       float64
 12  promo_discount_type_2  0 non-null       float64
dtypes: datetime64[us](1), float64(7), str(5)
memory usage: 9.9 MB

In [9]:
df.describe(include="all")

,product_id,store_id,date,sales,revenue,stock,price,promo_type_1,promo_bin_1,promo_type_2,promo_bin_2,promo_discount_2,promo_discount_type_2
count,100000,100000,100000,100000.000000,100000.000000,100000.000000,98523.000000,100000,10950,100000,0.0,0.0,0.0
unique,320,117,NaN,NaN,NaN,NaN,NaN,10,5,1,NaN,NaN,NaN
top,P0438,S0038,NaN,NaN,NaN,NaN,NaN,PR14,verylow,PR03,NaN,NaN,NaN
freq,895,1886,NaN,NaN,NaN,NaN,NaN,89050,3940,100000,NaN,NaN,NaN
mean,NaN,NaN,2017-01-05 07:51:37.728000,0.531913,1.522948,15.935417,8.872408,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,2017-01-02 00:00:00,0.000000,0.000000,0.000000,0.250000,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,2017-01-03 00:00:00,0.000000,0.000000,4.000000,2.450000,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,2017-01-05 00:00:00,0.000000,0.000000,8.000000,5.750000,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,2017-01-07 00:00:00,0.000000,0.000000,16.000000,10.750000,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,2017-01-09 00:00:00,161.000000,737.920000,2892.000000,219.900000,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,2.492288,6.906786,40.998988,10.798131,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df.columns

Index(['product_id', 'store_id', 'date', 'sales', 'revenue', 'stock', 'price',
       'promo_type_1', 'promo_bin_1', 'promo_type_2', 'promo_bin_2',
       'promo_discount_2', 'promo_discount_type_2'],
      dtype='str')

Perform Data Quality Checks like check missing values, duplicate rows, unique values, etc.

In [11]:
# Check missing values
df.isna().sum()

product_id                    0
store_id                      0
date                          0
sales                         0
revenue                       0
stock                         0
price                      1477
promo_type_1                  0
promo_bin_1               89050
promo_type_2                  0
promo_bin_2              100000
promo_discount_2         100000
promo_discount_type_2    100000
dtype: int64

In [12]:
# Check duplicate rows:
df.duplicated().sum()

np.int64(0)

In [13]:
# Check unique values:
df.nunique()

product_id                320
store_id                  117
date                        8
sales                     421
revenue                  1134
stock                     680
price                     190
promo_type_1               10
promo_bin_1                 5
promo_type_2                1
promo_bin_2                 0
promo_discount_2            0
promo_discount_type_2       0
dtype: int64

In [14]:
# Check invalid numerical values:
(df["revenue"] <= 0).sum()
(df["sales"] <= 0).sum()

np.int64(80163)

In [15]:
# Clean the data where necessary:
df = df.drop_duplicates()

In [16]:
# 4. Create useful features

In [ ]:
df[""]